<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Referencias a tu capa de Application y Domain -->
    <ProjectReference Include="../../../../Application/ConfiguracionSistemaBC.Application.csproj" />
    <ProjectReference Include="../../../../Domain/ConfiguracionSistemaBC.Domain.csproj" />
  </ItemGroup>

</Project>
