<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ControlCajaBC.Application.csproj" />
    <ProjectReference Include="..\Domain\ControlCajaBC.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Output\Persistence\InMemory\ControlCajaBC.Adapters.InMemory.csproj" />
    <ProjectReference Include="Output\Persistence\EFCore\ControlCajaBC.Adapters.EFCore\ControlCajaBC.Adapters.EFCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Evita compilar código de proyectos anidados -->
  <Compile Remove="Output\Persistence\**\*.cs" />
  <!-- Evita cualquier archivo generado en obj -->
  <Compile Remove="obj\**\*.cs" />
  <Compile Remove="$(BaseIntermediateOutputPath)**\*.cs" />
  </ItemGroup>
</Project>